STOP_WORDS = {
    "mod",
    "mods",
    "模组",
    "tag",
    "tags",
    "tagged",
    "标签",
    "named",
    "called",
    "titled",
    "title",
    "name",
    "version",
    "versions",
    "版本",
    "nexus",
    "nexusmods",
    "loverslab",
    "lovers",
    "lab",
    "最近",
    "最新",
    "更新",
    "过去",
    "近",
    "天",
    "日",
    "周",
    "星期",
    "个月",
    "月",
    "热门",
    "最多",
    "最",
    "最高",
    "至少",
    "不少于",
    "不低于",
    "超过",
    "大于",
    "以上",
    "最少",
    "最低",
    "哪些",
    "有哪些",
    "有没有",
    "只看",
    "不要",
    "排除",
    "不看",
    "别看",
    "查看",
    "看看",
    "相关",
    "类似",
    "继续",
    "这个",
    "这两个",
    "两个",
    "风格",
    "同类",
    "同款",
    "保持",
    "还有",
    "其他",
    "再找",
    "more",
    "not",
    "from",
    "over",
    "but",
    "and",
    "or",
    "except",
    "excluding",
    "exclude",
    "without",
    "minimum",
    "min",
    "no",
    "than",
    "at",
    "last",
    "past",
    "within",
    "recent",
    "recently",
    "latest",
    "newest",
    "updated",
    "update",
    "day",
    "days",
    "week",
    "weeks",
    "month",
    "months",
    "most",
    "top",
    "popular",
    "popularity",
    "download",
    "downloads",
    "downloaded",
    "endorsement",
    "endorsements",
    "endorsed",
    "endorse",
    "view",
    "views",
    "likes",
    "rated",
    "rating",
    "highest",
    "least",
    "lowest",
    "fewest",
    "similar",
    "related",
    "same",
    "other",
    "another",
    "different",
    "this",
    "like",
    "find",
    "search",
    "show",
    "want",
    "need",
    "looking",
    "look",
    "looks",
    "make",
    "makes",
    "turn",
    "turns",
    "into",
    "kind",
    "style",
    "aesthetic",
    "character",
    "player",
    "npc",
    "please",
    "any",
    "some",
    "adult",
    "nsfw",
    "sfw",
    "r18",
    "safe",
    "non",
    "author",
    "creator",
    "modder",
    "by",
    "risk",
    "risks",
    "install",
    "installation",
    "requirement",
    "requirements",
    "dependency",
    "dependencies",
    "compatible",
    "compatibility",
    "conflict",
    "conflicts",
    "alternative",
    "alternatives",
    "replacement",
    "replacements",
    "substitute",
    "substitutes",
    "instead",
    "safer",
    "stable",
    "stability",
    "which",
    "compare",
    "comparison",
    "better",
    "recommend",
    "beginner",
    "beginners",
    "lower",
    "less",
    "risky",
    "i",
    "me",
    "my",
    "a",
    "an",
    "the",
    "to",
    "for",
    "with",
    "of",
    "的",
    "和",
    "了",
    "我",
    "想",
    "让",
    "把",
    "角色",
    "人物",
    "主角",
    "变成",
    "变得",
    "那种",
    "这种",
    "一点",
    "一些",
    "审美",
    "效果",
    "感觉",
    "夸张",
    "成人",
    "非成人",
    "内容",
    "但",
    "作者",
    "创作者",
    "安装",
    "风险",
    "前置",
    "依赖",
    "兼容",
    "冲突",
    "替代",
    "替代品",
    "平替",
    "更稳",
    "更安全",
    "更合适",
    "哪个",
    "哪一个",
    "对比",
    "比较",
    "更适合",
    "更推荐",
    "风险更低",
    "新手",
    "高吗",
    "吗",
    "下载",
    "下载量",
    "唯一下载",
    "背书",
    "点赞",
    "喜欢",
    "浏览",
    "浏览量",
    "火",
    "发布",
    "创建",
}

CHINESE_QUERY_FILLERS = (
    "有什么",
    "有哪些",
    "有没有",
    "帮我找",
    "帮我看看",
    "我想找",
    "想找",
    "不要",
    "排除",
    "不看",
    "别看",
    "成人内容",
    "成人",
    "非成人",
    "内容",
    "但",
    "我想",
    "作者是",
    "作者",
    "创作者",
    "帮我",
    "让我",
    "让角色",
    "把角色",
    "角色",
    "人物",
    "主角",
    "变成",
    "变得",
    "那种",
    "这种",
    "审美",
    "效果",
    "感觉",
    "安装风险",
    "安装",
    "风险",
    "前置",
    "依赖",
    "兼容",
    "冲突",
    "替代品",
    "替代",
    "平替",
    "推荐",
    "推荐几个",
    "推荐一些",
    "换一个",
    "换一批",
    "更稳",
    "更安全",
    "更合适",
    "更兼容",
    "哪个",
    "哪一个",
    "对比",
    "比较",
    "更适合",
    "更推荐",
    "风险更低",
    "新手",
    "下载量",
    "下载",
    "唯一下载",
    "背书",
    "点赞",
    "喜欢",
    "浏览量",
    "浏览",
    "热门",
    "最多",
    "最",
    "最高",
    "至少",
    "不少于",
    "不低于",
    "超过",
    "大于",
    "以上",
    "最少",
    "最低",
    "火",
    "发布",
    "创建",
    "过去",
    "近",
    "天",
    "日",
    "周",
    "星期",
    "个月",
    "月",
    "查找",
    "搜索",
    "标签",
    "tag",
    "tags",
    "tagged",
    "named",
    "called",
    "titled",
    "title",
    "name",
    "version",
    "versions",
    "版本",
    "和",
    "相关的",
    "相关",
    "类似的",
    "类似",
    "继续",
    "这个",
    "这两个",
    "两个",
    "风格",
    "同类",
    "同款",
    "保持",
    "还有",
    "其他",
    "再找",
    "mod",
    "mods",
    "模组",
)

SEMANTIC_RULES: tuple[dict, ...] = (
    {
        "name": "bimbo",
        "markers": ["bimbo", "bimbo化", "bimbo风格"],
        "terms": ["bimbo"],
        "category_aliases": ["body", "presets"],
        "anchor": "bimbo",
        "domains": ["identity_style"],
    },
    {
        "name": "roleplay",
        "markers": ["扮演", "角色扮演", "roleplay", "role-play", "rp"],
        "terms": ["roleplay", "character progression", "scenario", "quest"],
        "category_aliases": ["gameplay", "quests"],
        "anchor": "roleplay",
        "domains": ["mechanics"],
    },
    {
        "name": "sexworker_style",
        "markers": ["妓女", "娼妓", "prostitute", "courtesan"],
        "terms": ["prostitute", "courtesan", "provocative", "lingerie"],
        "category_aliases": ["clothing", "outfit", "outfits", "服装"],
        "anchor": "sexworker_style",
        "domains": ["identity_style", "content_type"],
    },
    {
        "name": "framework",
        "markers": ["体系", "系统", "核心框架", "framework", "system"],
        "terms": ["framework", "system", "core", "mod framework"],
        "category_aliases": ["utilities", "modders resources", "framework"],
        "anchor": "framework",
        "domains": ["content_type"],
    },
    {
        "name": "loverslab",
        "markers": ["loverslab", "lovers lab", "爱的实验室", "爱实验室", "爱之实验室"],
        "terms": ["loverslab"],
        "anchor": "loverslab",
        "domains": ["source_scope"],
    },
    {
        "name": "female",
        "markers": ["女性", "女装", "女款", "女士", "女人", "妹子", "female", "woman", "women", "girl"],
        "terms": ["female", "women", "girl", "cbbe", "unp", "bodyslide", "eve"],
    },
    {
        "name": "male",
        "markers": ["男性", "男装", "男款", "男士", "男人", "male", "man", "men", "boy"],
        "terms": ["male", "men", "himbo", "sos", "male body"],
    },
    {
        "name": "outfit",
        "markers": ["服装", "衣服", "衣装", "套装", "外观", "裙", "内衣", "outfit", "clothing", "dress", "robe"],
        "terms": ["outfit", "clothing", "dress", "robe", "bikini", "lingerie", "costume", "suit"],
        "category_aliases": ["clothing", "accessories", "outfit", "outfits", "服装"],
        "anchor": "outfit",
        "domains": ["content_type"],
    },
    {
        "name": "armor",
        "markers": ["护甲", "盔甲", "轻甲", "重甲", "甲", "armor", "armour", "light armor", "heavy armor"],
        "terms": ["armor", "armour", "light armor", "heavy armor", "clothing"],
        "category_aliases": ["armor", "armour", "轻甲", "护甲"],
    },
    {
        "name": "weapon",
        "markers": ["武器", "刀剑", "枪械", "弓箭", "weapon", "weapons", "sword", "gun", "bow"],
        "terms": ["weapon", "weapons", "sword", "gun", "bow"],
        "category_aliases": ["weapon", "weapons", "武器"],
    },
    {
        "name": "gameplay",
        "markers": ["玩法", "机制", "战斗", "生存", "任务", "平衡", "perk", "技能", "gameplay", "combat", "quest"],
        "terms": ["gameplay", "combat", "quest", "perk", "survival", "balance", "mechanics"],
        "category_aliases": ["gameplay", "combat", "quests", "skills", "perks", "游戏玩法"],
        "anchor": "gameplay",
        "domains": ["content_type", "mechanics"],
    },
    {
        "name": "pregnancy",
        "markers": ["怀孕", "妊娠", "pregnancy", "pregnant"],
        "terms": ["pregnancy", "pregnant", "fertility", "birth"],
        "anchor": "pregnancy",
        "domains": ["mechanics"],
    },
    {
        "name": "visual",
        "markers": ["画质", "画面", "材质", "纹理", "光照", "美化", "视觉", "graphics", "texture", "visual", "lighting"],
        "terms": ["graphics", "texture", "textures", "visual", "lighting", "environment", "reshade"],
        "category_aliases": ["graphics", "textures", "visuals", "environment", "models", "美化"],
    },
    {
        "name": "follower",
        "markers": ["随从", "同伴", "伙伴", "follower", "companion"],
        "terms": ["follower", "companion", "npc"],
        "category_aliases": ["followers", "companions", "npcs", "随从"],
    },
    {
        "name": "animation",
        "markers": ["动画", "动作", "姿势", "animation", "pose", "moveset"],
        "terms": ["animation", "animations", "pose", "moveset", "behavior"],
        "category_aliases": ["animation", "animations", "poses"],
    },
    {
        "name": "utility",
        "markers": ["工具", "框架", "修复", "补丁", "性能", "utility", "framework", "fix", "patch", "performance"],
        "terms": ["utility", "framework", "fix", "patch", "performance", "bugfix"],
        "category_aliases": ["utilities", "bug fixes", "patches", "modders resources"],
    },
    {
        "name": "cosmetic_face",
        "markers": ["玻尿酸", "肉毒", "botox", "botoxed", "hyaluronic"],
        "terms": ["玻尿酸", "botox", "botoxed", "hyaluronic"],
    },
)
