"""initial

Revision ID: 97340fefbb99
Revises: 
Create Date: 2026-05-17 09:51:50.262464

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '97340fefbb99'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matches_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_messages_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_sort_index'), ['sort_index'], unique=False)

    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('finished_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('items_scanned', sa.Integer(), nullable=False),
    sa.Column('items_matched', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('mods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('game', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('game_domain', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('tags_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('created_at_remote', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at_remote', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_at_remote', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('unique_downloads', sa.Integer(), nullable=True),
    sa.Column('endorsements', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('adult_content', sa.Boolean(), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('raw_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_seen_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_mod_source_external_id'),
    sqlite_autoincrement=True
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('recipient', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sent_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sqlite_autoincrement=True
    )
    op.create_table('system_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=True),
    sa.Column('related_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('watch_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('source_config_json', sa.Text(), nullable=True),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('notification_json', sa.Text(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('notify_on_update', sa.Boolean(), nullable=False),
    sa.Column('user_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_tags_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_known_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('last_known_updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_checked_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mod_id'),
    sqlite_autoincrement=True
    )
    op.create_table('mod_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('summary_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('generated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('mod_update_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('favorite_id', sa.Integer(), nullable=True),
    sa.Column('old_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('new_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('old_updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_changelog', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('change_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detected_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mod_update_events')
    op.drop_table('mod_summaries')
    op.drop_table('favorites')
    op.drop_table('watch_rules')
    op.drop_table('system_notifications')
    op.drop_table('settings')
    op.drop_table('notifications')
    op.drop_table('mods')
    op.drop_table('job_runs')
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_messages_sort_index'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_message_id'))

    op.drop_table('agent_messages')
    # ### end Alembic commands ###
